services:
  suprema:
    build: .
    container_name: suprema_allinone
    restart: unless-stopped
    env_file: .env
    ports:
      - "8508:8508"
      - "8510:8510"
    volumes:
      - ./logs:/var/log/supervisor
      - redis_data:/var/lib/redis
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8508/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  redis_data:
